### ISSUE TITLE
build cansandra docker image error

### ISSUE THREAD

**Issue by apachemycat** [Metaswitch/clearwater-docker#31]
when I build canandra docker image ,some error ocurred and can't pass ,following is err log 

Reading package lists...
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-security_main_binary-amd64_Packages.gz is not what the server reported 667375 667385
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-security_universe_binary-amd64_Packages.gz is not what the server reported 180006 180015
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package homestead-cassandra
E: Unable to locate package homestead-prov-cassandra
E: Unable to locate package homer-cassandra

The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes homestead-cassandra homestead-prov-cassandra homer-cassandra' returned a non-zero code: 100

**Comment by MatMeredith** [comment]
@apachemycat Apologies for this.   This error is because the version of clearwater-docker you are trying to build depends on the latest set of Clearwater binaries, but by default tries to install from http://repo.cw-ngv.com/stable.   This will be fixed when we cut release 108 (should be later today), or alternatively you can update base/Dockerfile to reference http://repo.cw-ngv.com/latest instead of http://repo.cw-ngv.com/stable.
