### ISSUE TITLE
ralf log has some warning

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#42]
19-10-2016 06:11:17.215 UTC Status httpstack.cpp:164: Binding HTTP TCP socket: address=172.17.1.12, port=10888
19-10-2016 06:11:18.433 UTC Status diameterresolver.cpp:62: Created Diameter resolver
19-10-2016 06:11:18.695 UTC Error dnscachedresolver.cpp:607: Failed to retrieve record for example.com: DNS server returned answer with no data
19-10-2016 06:11:18.958 UTC Error dnscachedresolver.cpp:607: Failed to retrieve record for _diameter._tcp.example.com: Domain name not found
19-10-2016 06:11:18.958 UTC Error dnscachedresolver.cpp:607: Failed to retrieve record for _diameter._sctp.example.com: Domain name not found
19-10-2016 06:11:18.958 UTC Error diameterstack.cpp:854: No Diameter peers have been found

**Comment by richardwhiuk** [comment]
It looks like you don't have a Diameter peer configured to perform Rf billing? Are you expecting to use Rf billing? If you are, then you need to configure DNS records so that Ralf can contact your CDF. If you aren't, then you don't need Ralf. To configure a CDF, either configure billing_realm or cdf_identity.

**Comment by eleanor-merry** [comment]
Closing as answered.
