### ISSUE TITLE
bono not connect chronos 

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#44]
bono log show it connect 127.0.0.1 for chronos ,not remote chronos address 

21-10-2016 06:57:59.940 UTC Status bono.cpp:3322: Create list of PBXes
21-10-2016 06:57:59.940 UTC Status main.cpp:1910: Creating connection to Chronos 127.0.0.1:7253 using 127.0.0.1:9888 as the callback URI
21-10-2016 06:57:59.941 UTC Status http_connection_pool.cpp:50: Connection pool will use a response timeout of 500ms
21-10-2016 06:57:59.941 UTC Status httpconnection.h:71: Configuring HTTP Connection
21-10-2016 06:57:59.941 UTC Status httpconnection.h:72:   Connection created for server 127.0.0.1:7253
21-10-2016 06:57:59.941 UTC Status main.cpp:1957: Using local store

**Comment by richardwhiuk** [comment]
This is because there's no configured hostname for your Chronos nodes.

What version of Clearwater are you using? The work under https://github.com/Metaswitch/clearwater-infrastructure/pull/375 should resolve this, so you might need to build with the latest images.

**Comment by richardwhiuk** [comment]
@graemerobertson correctly points out that Bono shouldn't be trying to connect to Chronos, so this is a bug.

**Comment by MatMeredith** [comment]
Bono actually isn't trying to connect to Chronos.   

All Sprout based processes create a "Chronos connection" object so that e.g. Sprout plugins can access this if they want to, but in the case of a Bono node this never gets used and no actual connection ever gets created.   We could not even create the connection object on a pure Bono node, but it's harmless and so I'm not convinced this change is worthwhile.   If we were to make this change there's a bunch of other stuff we could do too like not create memcached and SDM objects on Bono...

@richardwhiuk: Suggest this is live with / WAD...

**Comment by eleanor-merry** [comment]
Yes, this is live with. Our current model is that the base sprout creates the various connection, alarm, SDM objects, and makes them available to whatever package wants to use them. At some point, we'll probably change this, but for now this is working as designed.
